nginx:
  image: nginx:1.8
  ports:
    - "80:80"
  links:
    - php:fpm
  volumes:
    - /home/dhewana/conf/nginx.conf:/etc/nginx/nginx.conf
    - /home/dhewana/conf/conf.d:/etc/nginx/conf.d
    - /home/dhewana/www/public:/var/www/html
    - /home/dhewana/logs:/var/log/nginx
  restart: always

php:
  image: dhewana/php-fpm:5.6
  links:
    - memcached
    - redis
    - beanstalk
  volumes:
    - /home/dhewana/www/public:/var/www/html
  restart: always

memcached:
  image: memcached
  command:
#    - -d
    - -vv
    - -m 12
    - -c 2048
    - -r
    - logfile /dev/null
  restart: always

redis:
  image: redis:3.0.7
  restart: always

beanstalk:
  image: dhewana/beanstalk
  restart: always
