nginx:
  container_name: my_nginx
  image: nginx:1.8
  ports:
    - "80:80"
  links:
    - phpfpm
    - mysql
  volumes:
    - /home/user/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - /home/user/nginx/conf/conf.d:/etc/nginx/conf.d
    - /home/user/www/public:/var/www/html
    - /home/user/nginx/logs:/var/log/nginx
  restart: always

phpfpm:
  container_name: my_phpfpm
  image: dhewana/php-fpm:5.6
  links:
    - memcached
    - redis
    - beanstalk
  volumes:
    - /home/user/www/public:/var/www/html
  restart: always

memcached:
  container_name: my_memcached
  image: memcached
  command:
#    - -d
    - -vv
    - -m 12
    - -c 2048
    - -r
    - logfile /dev/null
  restart: always

redis:
  container_name: my_redis
  image: redis:3.0.7
  restart: always

beanstalk:
  container_name: my_beanstalk
  image: dhewana/beanstalk
  restart: always

mysql:
  container_name: my_mysql
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=<password>
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  restart: always
